package com.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OptionsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOptionsAllPropertiesEquals(Options expected, Options actual) {
        assertOptionsAutoGeneratedPropertiesEquals(expected, actual);
        assertOptionsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOptionsAllUpdatablePropertiesEquals(Options expected, Options actual) {
        assertOptionsUpdatableFieldsEquals(expected, actual);
        assertOptionsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOptionsAutoGeneratedPropertiesEquals(Options expected, Options actual) {
        assertThat(expected)
            .as("Verify Options auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOptionsUpdatableFieldsEquals(Options expected, Options actual) {
        assertThat(expected)
            .as("Verify Options relevant properties")
            .satisfies(e -> assertThat(e.getOptionText()).as("check optionText").isEqualTo(actual.getOptionText()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOptionsUpdatableRelationshipsEquals(Options expected, Options actual) {}
}
