package com.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserResponsesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserResponsesAllPropertiesEquals(UserResponses expected, UserResponses actual) {
        assertUserResponsesAutoGeneratedPropertiesEquals(expected, actual);
        assertUserResponsesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserResponsesAllUpdatablePropertiesEquals(UserResponses expected, UserResponses actual) {
        assertUserResponsesUpdatableFieldsEquals(expected, actual);
        assertUserResponsesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserResponsesAutoGeneratedPropertiesEquals(UserResponses expected, UserResponses actual) {
        assertThat(expected)
            .as("Verify UserResponses auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserResponsesUpdatableFieldsEquals(UserResponses expected, UserResponses actual) {
        assertThat(expected)
            .as("Verify UserResponses relevant properties")
            .satisfies(e -> assertThat(e.getResponseText()).as("check responseText").isEqualTo(actual.getResponseText()))
            .satisfies(e -> assertThat(e.getResponseDate()).as("check responseDate").isEqualTo(actual.getResponseDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserResponsesUpdatableRelationshipsEquals(UserResponses expected, UserResponses actual) {}
}
