package com.scb.fimob.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EthnicityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEthnicityAllPropertiesEquals(Ethnicity expected, Ethnicity actual) {
        assertEthnicityAutoGeneratedPropertiesEquals(expected, actual);
        assertEthnicityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEthnicityAllUpdatablePropertiesEquals(Ethnicity expected, Ethnicity actual) {
        assertEthnicityUpdatableFieldsEquals(expected, actual);
        assertEthnicityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEthnicityAutoGeneratedPropertiesEquals(Ethnicity expected, Ethnicity actual) {
        assertThat(expected)
            .as("Verify Ethnicity auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEthnicityUpdatableFieldsEquals(Ethnicity expected, Ethnicity actual) {
        assertThat(expected)
            .as("Verify Ethnicity relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getUrduName()).as("check urduName").isEqualTo(actual.getUrduName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEthnicityUpdatableRelationshipsEquals(Ethnicity expected, Ethnicity actual) {}
}
