package com.scb.fimob.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FimSettAcctHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFimSettAcctHistoryAllPropertiesEquals(FimSettAcctHistory expected, FimSettAcctHistory actual) {
        assertFimSettAcctHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertFimSettAcctHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFimSettAcctHistoryAllUpdatablePropertiesEquals(FimSettAcctHistory expected, FimSettAcctHistory actual) {
        assertFimSettAcctHistoryUpdatableFieldsEquals(expected, actual);
        assertFimSettAcctHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFimSettAcctHistoryAutoGeneratedPropertiesEquals(FimSettAcctHistory expected, FimSettAcctHistory actual) {
        assertThat(expected)
            .as("Verify FimSettAcctHistory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFimSettAcctHistoryUpdatableFieldsEquals(FimSettAcctHistory expected, FimSettAcctHistory actual) {
        assertThat(expected)
            .as("Verify FimSettAcctHistory relevant properties")
            .satisfies(e -> assertThat(e.getSettaccId()).as("check settaccId").isEqualTo(actual.getSettaccId()))
            .satisfies(e -> assertThat(e.getHistoryTs()).as("check historyTs").isEqualTo(actual.getHistoryTs()))
            .satisfies(e -> assertThat(e.getAccountId()).as("check accountId").isEqualTo(actual.getAccountId()))
            .satisfies(e -> assertThat(e.getSettAcctNbr()).as("check settAcctNbr").isEqualTo(actual.getSettAcctNbr()))
            .satisfies(e -> assertThat(e.getSettCcy()).as("check settCcy").isEqualTo(actual.getSettCcy()))
            .satisfies(e -> assertThat(e.getSettAcctStatus()).as("check settAcctStatus").isEqualTo(actual.getSettAcctStatus()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedTs()).as("check createdTs").isEqualTo(actual.getCreatedTs()))
            .satisfies(e -> assertThat(e.getUpdatedBy()).as("check updatedBy").isEqualTo(actual.getUpdatedBy()))
            .satisfies(e -> assertThat(e.getUpdatedTs()).as("check updatedTs").isEqualTo(actual.getUpdatedTs()))
            .satisfies(e -> assertThat(e.getRecordStatus()).as("check recordStatus").isEqualTo(actual.getRecordStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFimSettAcctHistoryUpdatableRelationshipsEquals(FimSettAcctHistory expected, FimSettAcctHistory actual) {}
}
