package com.simplerishta.cms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfileVerificationStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileVerificationStatusAllPropertiesEquals(
        ProfileVerificationStatus expected,
        ProfileVerificationStatus actual
    ) {
        assertProfileVerificationStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertProfileVerificationStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileVerificationStatusAllUpdatablePropertiesEquals(
        ProfileVerificationStatus expected,
        ProfileVerificationStatus actual
    ) {
        assertProfileVerificationStatusUpdatableFieldsEquals(expected, actual);
        assertProfileVerificationStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileVerificationStatusAutoGeneratedPropertiesEquals(
        ProfileVerificationStatus expected,
        ProfileVerificationStatus actual
    ) {
        assertThat(expected)
            .as("Verify ProfileVerificationStatus auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileVerificationStatusUpdatableFieldsEquals(
        ProfileVerificationStatus expected,
        ProfileVerificationStatus actual
    ) {
        assertThat(expected)
            .as("Verify ProfileVerificationStatus relevant properties")
            .satisfies(e -> assertThat(e.getAttributeName()).as("check attributeName").isEqualTo(actual.getAttributeName()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getVerifiedAt()).as("check verifiedAt").isEqualTo(actual.getVerifiedAt()))
            .satisfies(e -> assertThat(e.getVerifiedBy()).as("check verifiedBy").isEqualTo(actual.getVerifiedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileVerificationStatusUpdatableRelationshipsEquals(
        ProfileVerificationStatus expected,
        ProfileVerificationStatus actual
    ) {
        // empty method
    }
}
